# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 19:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0002_auto_20170210_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 10, 19, 46, 12, 289557)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=b'img/geeks/No_Image.jpg', upload_to=b'img/geeks'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 10, 19, 46, 12, 288723)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 10, 19, 46, 12, 290214)),
        ),
    ]
